dist: spec: Include bpftool man pages with correct extension in bpftool RPM
The previous kernel RPM spec file did not accurately specify the extension for
bpftool man pages. This could lead to build errors on certain architectures where
the generated man pages might use a different extension than the expected `.gz`.

For example, on LoongArch, building a kernel RPM could result in the following errors:
Error: File not found: ... /loongarch64/usr/share/man/man8/bpftool.8.gz
Error: File not found: ... /loongarch64/usr/share/man/man8/bpftool-*.8.gz

This is because the bpftool man pages are actually generated with the `.zst`
extension on LoongArch:
bpftool.8.zst      bpftool-cgroup.8.zst   bpftool-gen.8.zst   bpftool-link.8.zst
...

This commit modifies the kernel.template.spec file to use a wildcard extension
when including bpftool man pages. This ensures that all generated man pages are
included in the RPM package, regardless of their extension.

Signed-off-by: Ming Wang <wangming01@loongson.cn>